services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - 9870:9870  # HDFS web UI
      - 9000:9000  # HDFS namenode RPC  
    volumes:
      - ./hadoop_namenode:/hadoop/dfs/name  # Persistent storage  
    environment:
      - CLUSTER_NAME=test
      - HDFS_CONF_dfs_replication=1
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    ports:
      - 9864:9864  # HDFS datanode web UI
    volumes:
      - ./hadoop_datanode:/hadoop/dfs/data
    environment:
      - CLUSTER_NAME=test
      - HDFS_CONF_dfs_replication=1
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000

  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    depends_on:
      - namenode
      - datanode
    ports:
      - "8080:8080"   #  Spark Master UI
      - "7077:7077"   # Cluster connection port
    environment:
    - INIT_DAEMON_STEP=setup_spark
    - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
  spark-worker-1:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000


